/* This file is auto-generated from "httpurl.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef HTTPURL_P_H
#define HTTPURL_P_H

#include "httpurl_l.h"

struct GWEN_HTTP_URL {
  GWEN_LIST_ELEMENT(GWEN_HTTP_URL)
  int _usage;
  int _modified;

  char *protocol;
  char *server;
  int port;
  char *path;
  GWEN_DB_NODE *vars;
  char *url;
};







/**
* Returns the property @ref GWEN_HTTP_URL_Url
*/
GWENHYWFAR_API const char *GWEN_HttpUrl_GetUrl(const GWEN_HTTP_URL *el);
/**
* Set the property @ref GWEN_HTTP_URL_Url
*/
GWENHYWFAR_API void GWEN_HttpUrl_SetUrl(GWEN_HTTP_URL *el, const char *d);


#endif /* HTTPURL_P_H */
