/* This file is auto-generated from "httpcookie.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include "httpcookie_p.h"
#include <gwenhywfar/misc.h>
#include <gwenhywfar/db.h>
#include <gwenhywfar/debug.h>
#include <assert.h>
#include <stdlib.h>
#include <strings.h>


GWEN_LIST_FUNCTIONS(GWEN_HTTP_COOKIE, GWEN_HttpCookie)
GWEN_LIST2_FUNCTIONS(GWEN_HTTP_COOKIE, GWEN_HttpCookie)


GWEN_HTTP_COOKIE *GWEN_HttpCookie_new() {
  GWEN_HTTP_COOKIE *st;

  GWEN_NEW_OBJECT(GWEN_HTTP_COOKIE, st)
  st->_usage=1;
  GWEN_LIST_INIT(GWEN_HTTP_COOKIE, st)
  return st;
}


void GWEN_HttpCookie_free(GWEN_HTTP_COOKIE *st) {
  if (st) {
    assert(st->_usage);
    if (--(st->_usage)==0) {
  GWEN_LIST_FINI(GWEN_HTTP_COOKIE, st)
  GWEN_FREE_OBJECT(st);
    }
  }

}


GWEN_HTTP_COOKIE *GWEN_HttpCookie_dup(const GWEN_HTTP_COOKIE *d) {
  GWEN_HTTP_COOKIE *st;

  assert(d);
  st=GWEN_HttpCookie_new();
  if (d->name)
    st->name=strdup(d->name);
  if (d->value)
    st->value=strdup(d->value);
  if (d->expires)
    st->expires=GWEN_Time_dup(d->expires);
  if (d->path)
    st->path=strdup(d->path);
  if (d->domain)
    st->domain=strdup(d->domain);
  st->secure=d->secure;
  return st;
}


int GWEN_HttpCookie_toDb(const GWEN_HTTP_COOKIE *st, GWEN_DB_NODE *db) {
  assert(st);
  assert(db);
  if (st->name)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "name", st->name))
      return -1;
  if (st->value)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "value", st->value))
      return -1;
  if (st->expires)
    if (GWEN_Time_toDb(st->expires, GWEN_DB_GetGroup(db, GWEN_DB_FLAGS_DEFAULT, "expires")))
      return -1;
  if (st->path)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "path", st->path))
      return -1;
  if (st->domain)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "domain", st->domain))
      return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "secure", st->secure))
    return -1;
  return 0;
}


GWEN_HTTP_COOKIE *GWEN_HttpCookie_fromDb(GWEN_DB_NODE *db) {
GWEN_HTTP_COOKIE *st;

  assert(db);
  st=GWEN_HttpCookie_new();
  GWEN_HttpCookie_SetName(st, GWEN_DB_GetCharValue(db, "name", 0, 0));
  GWEN_HttpCookie_SetValue(st, GWEN_DB_GetCharValue(db, "value", 0, 0));
  if (1) {
    GWEN_DB_NODE *dbT;

    dbT=GWEN_DB_GetGroup(db, GWEN_PATH_FLAGS_NAMEMUSTEXIST, "expires");
    if (dbT) st->expires=GWEN_Time_fromDb(dbT);
  }
  GWEN_HttpCookie_SetPath(st, GWEN_DB_GetCharValue(db, "path", 0, 0));
  GWEN_HttpCookie_SetDomain(st, GWEN_DB_GetCharValue(db, "domain", 0, 0));
  GWEN_HttpCookie_SetSecure(st, GWEN_DB_GetIntValue(db, "secure", 0, 0));
  st->_modified=0;
  return st;
}


const char *GWEN_HttpCookie_GetName(const GWEN_HTTP_COOKIE *st) {
  assert(st);
  return st->name;
}


void GWEN_HttpCookie_SetName(GWEN_HTTP_COOKIE *st, const char *d) {
  assert(st);
  if (d)
    st->name=strdup(d);
  else
    st->name=0;
  st->_modified=1;
}




const char *GWEN_HttpCookie_GetValue(const GWEN_HTTP_COOKIE *st) {
  assert(st);
  return st->value;
}


void GWEN_HttpCookie_SetValue(GWEN_HTTP_COOKIE *st, const char *d) {
  assert(st);
  if (d)
    st->value=strdup(d);
  else
    st->value=0;
  st->_modified=1;
}




const GWEN_TIME *GWEN_HttpCookie_GetExpires(const GWEN_HTTP_COOKIE *st) {
  assert(st);
  return st->expires;
}


void GWEN_HttpCookie_SetExpires(GWEN_HTTP_COOKIE *st, const GWEN_TIME *d) {
  assert(st);
  if (d)
    st->expires=GWEN_Time_dup(d);
  else
    st->expires=0;
  st->_modified=1;
}




const char *GWEN_HttpCookie_GetPath(const GWEN_HTTP_COOKIE *st) {
  assert(st);
  return st->path;
}


void GWEN_HttpCookie_SetPath(GWEN_HTTP_COOKIE *st, const char *d) {
  assert(st);
  if (d)
    st->path=strdup(d);
  else
    st->path=0;
  st->_modified=1;
}




const char *GWEN_HttpCookie_GetDomain(const GWEN_HTTP_COOKIE *st) {
  assert(st);
  return st->domain;
}


void GWEN_HttpCookie_SetDomain(GWEN_HTTP_COOKIE *st, const char *d) {
  assert(st);
  if (d)
    st->domain=strdup(d);
  else
    st->domain=0;
  st->_modified=1;
}




int GWEN_HttpCookie_GetSecure(const GWEN_HTTP_COOKIE *st) {
  assert(st);
  return st->secure;
}


void GWEN_HttpCookie_SetSecure(GWEN_HTTP_COOKIE *st, int d) {
  assert(st);
  st->secure=d;
  st->_modified=1;
}




int GWEN_HttpCookie_IsModified(const GWEN_HTTP_COOKIE *st) {
  assert(st);
  return st->_modified;
}


void GWEN_HttpCookie_SetModified(GWEN_HTTP_COOKIE *st, int i) {
  assert(st);
  st->_modified=i;
}


void GWEN_HttpCookie_Attach(GWEN_HTTP_COOKIE *st) {
  assert(st);
  st->_usage++;
}
GWEN_HTTP_COOKIE *GWEN_HttpCookie_List2__freeAll_cb(GWEN_HTTP_COOKIE *st, void *user_data) {
  GWEN_HttpCookie_free(st);
return 0;
}


void GWEN_HttpCookie_List2_freeAll(GWEN_HTTP_COOKIE_LIST2 *stl) {
  if (stl) {
    GWEN_HttpCookie_List2_ForEach(stl, GWEN_HttpCookie_List2__freeAll_cb, 0);
    GWEN_HttpCookie_List2_free(stl); 
  }
}




GWEN_HTTP_COOKIE_LIST *GWEN_HttpCookie_List_dup(const GWEN_HTTP_COOKIE_LIST *stl) {
  if (stl) {
    GWEN_HTTP_COOKIE_LIST *nl;
    GWEN_HTTP_COOKIE *e;

    nl=GWEN_HttpCookie_List_new();
    e=GWEN_HttpCookie_List_First(stl);
    while(e) {
      GWEN_HTTP_COOKIE *ne;

      ne=GWEN_HttpCookie_dup(e);
      assert(ne);
      GWEN_HttpCookie_List_Add(ne, nl);
      e=GWEN_HttpCookie_List_Next(e);
    } /* while (e) */
    return nl;
  }
  else
    return 0;
}



