/* This file is auto-generated from "httpurl.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef HTTPURL_L_H
#define HTTPURL_L_H

/** @page P_GWEN_HTTP_URL_LIB GWEN_HttpUrl (lib)
This page describes the properties of GWEN_HTTP_URL
*/
#include "httpurl.h"

#ifdef __cplusplus
extern "C" {
#endif









#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* HTTPURL_L_H */
