/* This file is auto-generated from "httpcookie.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef HTTPCOOKIE_L_H
#define HTTPCOOKIE_L_H

/** @page P_GWEN_HTTP_COOKIE_LIB GWEN_HttpCookie (lib)
This page describes the properties of GWEN_HTTP_COOKIE
*/
#include "httpcookie.h"

#ifdef __cplusplus
extern "C" {
#endif









#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* HTTPCOOKIE_L_H */
