/**********************************************************
 * This file has been automatically created by "typemaker2"
 * from the file "testmodule.xml".
 * Please do not edit this file, all changes will be lost.
 * Better edit the mentioned source file instead.
 **********************************************************/

#ifndef GWEN_TEST_MODULE_TESTMODULE_P_H
#define GWEN_TEST_MODULE_TESTMODULE_P_H

#include "./testmodule.h"


#ifdef __cplusplus
extern "C" {
#endif

struct GWEN_TEST_MODULE {
  GWEN_INHERIT_ELEMENT(GWEN_TEST_MODULE)
  GWEN_TREE2_ELEMENT(GWEN_TEST_MODULE)
  int _refCount;
  uint32_t id;
  char *name;
  char *description;
  int result;
  GWEN_DB_NODE *paramsDb;
  GWEN_TEST_MODULE_TEST_FN testFn;
};

/** Getter.
 * Use this function to get the member "paramsDb" (see @ref GWEN_TEST_MODULE_paramsDb)
*/
const GWEN_DB_NODE *GWEN_Test_Module_GetParamsDb(const GWEN_TEST_MODULE *p_struct);

/** Setter.
 * Use this function to set the member "paramsDb" (see @ref GWEN_TEST_MODULE_paramsDb)
*/
void GWEN_Test_Module_SetParamsDb(GWEN_TEST_MODULE *p_struct, const GWEN_DB_NODE *p_src);

#ifdef __cplusplus
}
#endif

#endif

