/* This file is auto-generated from "request.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef REQUEST_L_H
#define REQUEST_L_H

/** @page P_GWEN_IPC_REQUEST_LIB GWEN_IpcRequest (lib)
This page describes the properties of GWEN_IPC_REQUEST
*/
#include "request.h"

#ifdef __cplusplus
extern "C" {
#endif












#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* REQUEST_L_H */
