/**********************************************************
 * This file has been automatically created by "typemaker2"
 * from the file "gwen_sar_fileheader.xml".
 * Please do not edit this file, all changes will be lost.
 * Better edit the mentioned source file instead.
 **********************************************************/

#ifndef GWEN_SAR_FILEHEADER_P_H
#define GWEN_SAR_FILEHEADER_P_H

#include "gwen_sar_fileheader_l.h"


#ifdef __cplusplus
extern "C" {
#endif

struct GWEN_SAR_FILEHEADER {
  GWEN_LIST_ELEMENT(GWEN_SAR_FILEHEADER)
  int _refCount;
  int status;
  uint32_t flags;
  char *path;
  int fileType;
  uint32_t permissions;
  GWEN_TIME *atime;
  GWEN_TIME *mtime;
  GWEN_TIME *ctime;
  uint64_t fileSize;
  uint64_t headerStartPos; /* volatile */
  uint64_t headerSize; /* volatile */
  uint64_t dataPos; /* volatile */
  uint64_t dataSize; /* volatile */
  uint64_t hashPos; /* volatile */
};

#ifdef __cplusplus
}
#endif

#endif

