/* This file is auto-generated from "url.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef URL_P_H
#define URL_P_H

#include "url_l.h"


struct GWEN_URL {
  GWEN_LIST_ELEMENT(GWEN_URL)
  int _usage;
  int _modified;

  char *protocol;
  char *server;
  int port;
  char *path;
  GWEN_DB_NODE *vars;
  char *url;
};







/**
* Returns the property @ref GWEN_URL_Url
*/
GWENHYWFAR_API const char *GWEN_Url_GetUrl(const GWEN_URL *el);
/**
* Set the property @ref GWEN_URL_Url
*/
GWENHYWFAR_API void GWEN_Url_SetUrl(GWEN_URL *el, const char *d);


#endif /* URL_P_H */
