/* This file is auto-generated from "url.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef URL_L_H
#define URL_L_H

/** @page P_GWEN_URL_LIB GWEN_Url (lib)
This page describes the properties of GWEN_URL
*/
#include "url.h"

#ifdef __cplusplus
extern "C" {
#endif












#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* URL_L_H */
