/* This file is auto-generated from "crypttoken_user.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef CRYPTTOKEN_USER_L_H
#define CRYPTTOKEN_USER_L_H

/** @page P_GWEN_CRYPTTOKEN_USER_LIB GWEN_CryptToken_User (lib)
This page describes the properties of GWEN_CRYPTTOKEN_USER
*/
#include "crypttoken_user.h"

#ifdef __cplusplus
extern "C" {
#endif













#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* CRYPTTOKEN_USER_L_H */
