/* This file is auto-generated from "crypttoken_user.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include "crypttoken_user_p.h"
#include <gwenhywfar/misc.h>
#include <gwenhywfar/db.h>
#include <gwenhywfar/debug.h>
#include <assert.h>
#include <stdlib.h>
#include <strings.h>


GWEN_LIST_FUNCTIONS(GWEN_CRYPTTOKEN_USER, GWEN_CryptToken_User)
GWEN_LIST2_FUNCTIONS(GWEN_CRYPTTOKEN_USER, GWEN_CryptToken_User)


GWEN_CRYPTTOKEN_USER *GWEN_CryptToken_User_new() {
  GWEN_CRYPTTOKEN_USER *st;

  GWEN_NEW_OBJECT(GWEN_CRYPTTOKEN_USER, st)
  st->_usage=1;
  GWEN_LIST_INIT(GWEN_CRYPTTOKEN_USER, st)
  return st;
}


void GWEN_CryptToken_User_free(GWEN_CRYPTTOKEN_USER *st) {
  if (st) {
    assert(st->_usage);
    if (--(st->_usage)==0) {
  if (st->serviceId)
    free(st->serviceId);
  if (st->userId)
    free(st->userId);
  if (st->userName)
    free(st->userName);
  if (st->peerId)
    free(st->peerId);
  if (st->peerName)
    free(st->peerName);
  if (st->address)
    free(st->address);
  if (st->systemId)
    free(st->systemId);
  GWEN_LIST_FINI(GWEN_CRYPTTOKEN_USER, st)
  GWEN_FREE_OBJECT(st);
    }
  }

}


GWEN_CRYPTTOKEN_USER *GWEN_CryptToken_User_dup(const GWEN_CRYPTTOKEN_USER *d) {
  GWEN_CRYPTTOKEN_USER *st;

  assert(d);
  st=GWEN_CryptToken_User_new();
  st->id=d->id;
  if (d->serviceId)
    st->serviceId=strdup(d->serviceId);
  if (d->userId)
    st->userId=strdup(d->userId);
  if (d->userName)
    st->userName=strdup(d->userName);
  if (d->peerId)
    st->peerId=strdup(d->peerId);
  if (d->peerName)
    st->peerName=strdup(d->peerName);
  if (d->address)
    st->address=strdup(d->address);
  st->port=d->port;
  if (d->systemId)
    st->systemId=strdup(d->systemId);
  st->contextId=d->contextId;
  return st;
}


int GWEN_CryptToken_User_toDb(const GWEN_CRYPTTOKEN_USER *st, GWEN_DB_NODE *db) {
  assert(st);
  assert(db);
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "id", st->id))
    return -1;
  if (st->serviceId)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "serviceId", st->serviceId))
      return -1;
  if (st->userId)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "userId", st->userId))
      return -1;
  if (st->userName)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "userName", st->userName))
      return -1;
  if (st->peerId)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "peerId", st->peerId))
      return -1;
  if (st->peerName)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "peerName", st->peerName))
      return -1;
  if (st->address)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "address", st->address))
      return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "port", st->port))
    return -1;
  if (st->systemId)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "systemId", st->systemId))
      return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "contextId", st->contextId))
    return -1;
  return 0;
}


GWEN_CRYPTTOKEN_USER *GWEN_CryptToken_User_fromDb(GWEN_DB_NODE *db) {
GWEN_CRYPTTOKEN_USER *st;

  assert(db);
  st=GWEN_CryptToken_User_new();
  GWEN_CryptToken_User_SetId(st, GWEN_DB_GetIntValue(db, "id", 0, 0));
  GWEN_CryptToken_User_SetServiceId(st, GWEN_DB_GetCharValue(db, "serviceId", 0, 0));
  GWEN_CryptToken_User_SetUserId(st, GWEN_DB_GetCharValue(db, "userId", 0, 0));
  GWEN_CryptToken_User_SetUserName(st, GWEN_DB_GetCharValue(db, "userName", 0, 0));
  GWEN_CryptToken_User_SetPeerId(st, GWEN_DB_GetCharValue(db, "peerId", 0, 0));
  GWEN_CryptToken_User_SetPeerName(st, GWEN_DB_GetCharValue(db, "peerName", 0, 0));
  GWEN_CryptToken_User_SetAddress(st, GWEN_DB_GetCharValue(db, "address", 0, 0));
  GWEN_CryptToken_User_SetPort(st, GWEN_DB_GetIntValue(db, "port", 0, 0));
  GWEN_CryptToken_User_SetSystemId(st, GWEN_DB_GetCharValue(db, "systemId", 0, 0));
  GWEN_CryptToken_User_SetContextId(st, GWEN_DB_GetIntValue(db, "contextId", 0, 0));
  st->_modified=0;
  return st;
}


GWEN_TYPE_UINT32 GWEN_CryptToken_User_GetId(const GWEN_CRYPTTOKEN_USER *st) {
  assert(st);
  return st->id;
}


void GWEN_CryptToken_User_SetId(GWEN_CRYPTTOKEN_USER *st, GWEN_TYPE_UINT32 d) {
  assert(st);
  st->id=d;
  st->_modified=1;
}


const char *GWEN_CryptToken_User_GetServiceId(const GWEN_CRYPTTOKEN_USER *st) {
  assert(st);
  return st->serviceId;
}


void GWEN_CryptToken_User_SetServiceId(GWEN_CRYPTTOKEN_USER *st, const char *d) {
  assert(st);
  if (st->serviceId)
    free(st->serviceId);
  if (d)
    st->serviceId=strdup(d);
  else
    st->serviceId=0;
  st->_modified=1;
}


const char *GWEN_CryptToken_User_GetUserId(const GWEN_CRYPTTOKEN_USER *st) {
  assert(st);
  return st->userId;
}


void GWEN_CryptToken_User_SetUserId(GWEN_CRYPTTOKEN_USER *st, const char *d) {
  assert(st);
  if (st->userId)
    free(st->userId);
  if (d)
    st->userId=strdup(d);
  else
    st->userId=0;
  st->_modified=1;
}


const char *GWEN_CryptToken_User_GetUserName(const GWEN_CRYPTTOKEN_USER *st) {
  assert(st);
  return st->userName;
}


void GWEN_CryptToken_User_SetUserName(GWEN_CRYPTTOKEN_USER *st, const char *d) {
  assert(st);
  if (st->userName)
    free(st->userName);
  if (d)
    st->userName=strdup(d);
  else
    st->userName=0;
  st->_modified=1;
}


const char *GWEN_CryptToken_User_GetPeerId(const GWEN_CRYPTTOKEN_USER *st) {
  assert(st);
  return st->peerId;
}


void GWEN_CryptToken_User_SetPeerId(GWEN_CRYPTTOKEN_USER *st, const char *d) {
  assert(st);
  if (st->peerId)
    free(st->peerId);
  if (d)
    st->peerId=strdup(d);
  else
    st->peerId=0;
  st->_modified=1;
}


const char *GWEN_CryptToken_User_GetPeerName(const GWEN_CRYPTTOKEN_USER *st) {
  assert(st);
  return st->peerName;
}


void GWEN_CryptToken_User_SetPeerName(GWEN_CRYPTTOKEN_USER *st, const char *d) {
  assert(st);
  if (st->peerName)
    free(st->peerName);
  if (d)
    st->peerName=strdup(d);
  else
    st->peerName=0;
  st->_modified=1;
}


const char *GWEN_CryptToken_User_GetAddress(const GWEN_CRYPTTOKEN_USER *st) {
  assert(st);
  return st->address;
}


void GWEN_CryptToken_User_SetAddress(GWEN_CRYPTTOKEN_USER *st, const char *d) {
  assert(st);
  if (st->address)
    free(st->address);
  if (d)
    st->address=strdup(d);
  else
    st->address=0;
  st->_modified=1;
}


int GWEN_CryptToken_User_GetPort(const GWEN_CRYPTTOKEN_USER *st) {
  assert(st);
  return st->port;
}


void GWEN_CryptToken_User_SetPort(GWEN_CRYPTTOKEN_USER *st, int d) {
  assert(st);
  st->port=d;
  st->_modified=1;
}


const char *GWEN_CryptToken_User_GetSystemId(const GWEN_CRYPTTOKEN_USER *st) {
  assert(st);
  return st->systemId;
}


void GWEN_CryptToken_User_SetSystemId(GWEN_CRYPTTOKEN_USER *st, const char *d) {
  assert(st);
  if (st->systemId)
    free(st->systemId);
  if (d)
    st->systemId=strdup(d);
  else
    st->systemId=0;
  st->_modified=1;
}


GWEN_TYPE_UINT32 GWEN_CryptToken_User_GetContextId(const GWEN_CRYPTTOKEN_USER *st) {
  assert(st);
  return st->contextId;
}


void GWEN_CryptToken_User_SetContextId(GWEN_CRYPTTOKEN_USER *st, GWEN_TYPE_UINT32 d) {
  assert(st);
  st->contextId=d;
  st->_modified=1;
}


int GWEN_CryptToken_User_IsModified(const GWEN_CRYPTTOKEN_USER *st) {
  assert(st);
  return st->_modified;
}


void GWEN_CryptToken_User_SetModified(GWEN_CRYPTTOKEN_USER *st, int i) {
  assert(st);
  st->_modified=i;
}


void GWEN_CryptToken_User_Attach(GWEN_CRYPTTOKEN_USER *st) {
  assert(st);
  st->_usage++;
}
GWEN_CRYPTTOKEN_USER *GWEN_CryptToken_User_List2__freeAll_cb(GWEN_CRYPTTOKEN_USER *st, void *user_data) {
  GWEN_CryptToken_User_free(st);
return 0;
}


void GWEN_CryptToken_User_List2_freeAll(GWEN_CRYPTTOKEN_USER_LIST2 *stl) {
  if (stl) {
    GWEN_CryptToken_User_List2_ForEach(stl, GWEN_CryptToken_User_List2__freeAll_cb, 0);
    GWEN_CryptToken_User_List2_free(stl); 
  }
}




GWEN_CRYPTTOKEN_USER_LIST *GWEN_CryptToken_User_List_dup(const GWEN_CRYPTTOKEN_USER_LIST *stl) {
  if (stl) {
    GWEN_CRYPTTOKEN_USER_LIST *nl;
    GWEN_CRYPTTOKEN_USER *e;

    nl=GWEN_CryptToken_User_List_new();
    e=GWEN_CryptToken_User_List_First(stl);
    while(e) {
      GWEN_CRYPTTOKEN_USER *ne;

      ne=GWEN_CryptToken_User_dup(e);
      assert(ne);
      GWEN_CryptToken_User_List_Add(ne, nl);
      e=GWEN_CryptToken_User_List_Next(e);
    } /* while (e) */
    return nl;
  }
  else
    return 0;
}



