/* This file is auto-generated from "crypttoken_user.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef CRYPTTOKEN_USER_P_H
#define CRYPTTOKEN_USER_P_H

#include "crypttoken_user_l.h"

struct GWEN_CRYPTTOKEN_USER {
  GWEN_LIST_ELEMENT(GWEN_CRYPTTOKEN_USER)
  int _usage;
  int _modified;

  GWEN_TYPE_UINT32 id;
  char *serviceId;
  char *userId;
  char *userName;
  char *peerId;
  char *peerName;
  char *address;
  int port;
  char *systemId;
  GWEN_TYPE_UINT32 contextId;
};













#endif /* CRYPTTOKEN_USER_P_H */
