/* This file is auto-generated from "ssl_cert_descr.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef SSL_CERT_DESCR_P_H
#define SSL_CERT_DESCR_P_H

#include "ssl_cert_descr_l.h"


struct GWEN_SSLCERTDESCR {
  GWEN_LIST_ELEMENT(GWEN_SSLCERTDESCR)
  int _usage;
  int _modified;

  char *countryName;
  char *commonName;
  char *organizationName;
  char *organizationalUnitName;
  char *localityName;
  char *stateOrProvinceName;
  GWEN_TIME *notBefore;
  GWEN_TIME *notAfter;
  char *ipAddress;
  char *fingerPrint;
  char *pubKeyModulus;
  char *pubKeyExponent;
  char *statusText;
  int isError;
  uint32_t statusFlags;
};


















#endif /* SSL_CERT_DESCR_P_H */
