/* This file is auto-generated from "ct_context.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include "ct_context_p.h"
#include <gwenhywfar/misc.h>
#include <gwenhywfar/db.h>
#include <gwenhywfar/debug.h>
#include <assert.h>
#include <stdlib.h>
#include <strings.h>

#include <gwenhywfar/types.h>


GWEN_INHERIT_FUNCTIONS(GWEN_CRYPT_TOKEN_CONTEXT)
GWEN_LIST_FUNCTIONS(GWEN_CRYPT_TOKEN_CONTEXT, GWEN_Crypt_Token_Context)
GWEN_LIST2_FUNCTIONS(GWEN_CRYPT_TOKEN_CONTEXT, GWEN_Crypt_Token_Context)




GWEN_CRYPT_TOKEN_CONTEXT *GWEN_Crypt_Token_Context_new() {
  GWEN_CRYPT_TOKEN_CONTEXT *st;

  GWEN_NEW_OBJECT(GWEN_CRYPT_TOKEN_CONTEXT, st)
  st->_usage=1;
  GWEN_INHERIT_INIT(GWEN_CRYPT_TOKEN_CONTEXT, st)
  GWEN_LIST_INIT(GWEN_CRYPT_TOKEN_CONTEXT, st)
  return st;
}


void GWEN_Crypt_Token_Context_free(GWEN_CRYPT_TOKEN_CONTEXT *st) {
  if (st) {
    assert(st->_usage);
    if (--(st->_usage)==0) {
  GWEN_INHERIT_FINI(GWEN_CRYPT_TOKEN_CONTEXT, st)
  if (st->serviceId)
    free(st->serviceId);
  if (st->userId)
    free(st->userId);
  if (st->userName)
    free(st->userName);
  if (st->peerId)
    free(st->peerId);
  if (st->peerName)
    free(st->peerName);
  if (st->address)
    free(st->address);
  if (st->systemId)
    free(st->systemId);
  GWEN_LIST_FINI(GWEN_CRYPT_TOKEN_CONTEXT, st)
  GWEN_FREE_OBJECT(st);
    }
  }

}


GWEN_CRYPT_TOKEN_CONTEXT *GWEN_Crypt_Token_Context_dup(const GWEN_CRYPT_TOKEN_CONTEXT *d) {
  GWEN_CRYPT_TOKEN_CONTEXT *st;

  assert(d);
  st=GWEN_Crypt_Token_Context_new();
  st->id=d->id;
  st->signKeyId=d->signKeyId;
  st->verifyKeyId=d->verifyKeyId;
  st->encipherKeyId=d->encipherKeyId;
  st->decipherKeyId=d->decipherKeyId;
  st->authSignKeyId=d->authSignKeyId;
  st->authVerifyKeyId=d->authVerifyKeyId;
  if (d->serviceId)
    st->serviceId=strdup(d->serviceId);
  if (d->userId)
    st->userId=strdup(d->userId);
  if (d->userName)
    st->userName=strdup(d->userName);
  if (d->peerId)
    st->peerId=strdup(d->peerId);
  if (d->peerName)
    st->peerName=strdup(d->peerName);
  if (d->address)
    st->address=strdup(d->address);
  st->port=d->port;
  if (d->systemId)
    st->systemId=strdup(d->systemId);
  return st;
}


int GWEN_Crypt_Token_Context_toDb(const GWEN_CRYPT_TOKEN_CONTEXT *st, GWEN_DB_NODE *db) {
  assert(st);
  assert(db);
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "id", st->id))
    return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "signKeyId", st->signKeyId))
    return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "verifyKeyId", st->verifyKeyId))
    return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "encipherKeyId", st->encipherKeyId))
    return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "decipherKeyId", st->decipherKeyId))
    return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "authSignKeyId", st->authSignKeyId))
    return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "authVerifyKeyId", st->authVerifyKeyId))
    return -1;
  if (st->serviceId)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "serviceId", st->serviceId))
      return -1;
  if (st->userId)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "userId", st->userId))
      return -1;
  if (st->userName)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "userName", st->userName))
      return -1;
  if (st->peerId)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "peerId", st->peerId))
      return -1;
  if (st->peerName)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "peerName", st->peerName))
      return -1;
  if (st->address)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "address", st->address))
      return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "port", st->port))
    return -1;
  if (st->systemId)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "systemId", st->systemId))
      return -1;
  return 0;
}


int GWEN_Crypt_Token_Context_ReadDb(GWEN_CRYPT_TOKEN_CONTEXT *st, GWEN_DB_NODE *db) {
  assert(st);
  assert(db);
  GWEN_Crypt_Token_Context_SetId(st, GWEN_DB_GetIntValue(db, "id", 0, 0));
  GWEN_Crypt_Token_Context_SetSignKeyId(st, GWEN_DB_GetIntValue(db, "signKeyId", 0, 0));
  GWEN_Crypt_Token_Context_SetVerifyKeyId(st, GWEN_DB_GetIntValue(db, "verifyKeyId", 0, 0));
  GWEN_Crypt_Token_Context_SetEncipherKeyId(st, GWEN_DB_GetIntValue(db, "encipherKeyId", 0, 0));
  GWEN_Crypt_Token_Context_SetDecipherKeyId(st, GWEN_DB_GetIntValue(db, "decipherKeyId", 0, 0));
  GWEN_Crypt_Token_Context_SetAuthSignKeyId(st, GWEN_DB_GetIntValue(db, "authSignKeyId", 0, 0));
  GWEN_Crypt_Token_Context_SetAuthVerifyKeyId(st, GWEN_DB_GetIntValue(db, "authVerifyKeyId", 0, 0));
  GWEN_Crypt_Token_Context_SetServiceId(st, GWEN_DB_GetCharValue(db, "serviceId", 0, 0));
  GWEN_Crypt_Token_Context_SetUserId(st, GWEN_DB_GetCharValue(db, "userId", 0, 0));
  GWEN_Crypt_Token_Context_SetUserName(st, GWEN_DB_GetCharValue(db, "userName", 0, 0));
  GWEN_Crypt_Token_Context_SetPeerId(st, GWEN_DB_GetCharValue(db, "peerId", 0, 0));
  GWEN_Crypt_Token_Context_SetPeerName(st, GWEN_DB_GetCharValue(db, "peerName", 0, 0));
  GWEN_Crypt_Token_Context_SetAddress(st, GWEN_DB_GetCharValue(db, "address", 0, 0));
  GWEN_Crypt_Token_Context_SetPort(st, GWEN_DB_GetIntValue(db, "port", 0, 0));
  GWEN_Crypt_Token_Context_SetSystemId(st, GWEN_DB_GetCharValue(db, "systemId", 0, 0));
  return 0;
}


GWEN_CRYPT_TOKEN_CONTEXT *GWEN_Crypt_Token_Context_fromDb(GWEN_DB_NODE *db) {
  GWEN_CRYPT_TOKEN_CONTEXT *st;

  assert(db);
  st=GWEN_Crypt_Token_Context_new();
  GWEN_Crypt_Token_Context_ReadDb(st, db);
  st->_modified=0;
  return st;
}




uint32_t GWEN_Crypt_Token_Context_GetId(const GWEN_CRYPT_TOKEN_CONTEXT *st) {
  assert(st);
  return st->id;
}


void GWEN_Crypt_Token_Context_SetId(GWEN_CRYPT_TOKEN_CONTEXT *st, uint32_t d) {
  assert(st);
  st->id=d;
  st->_modified=1;
}




uint32_t GWEN_Crypt_Token_Context_GetSignKeyId(const GWEN_CRYPT_TOKEN_CONTEXT *st) {
  assert(st);
  return st->signKeyId;
}


void GWEN_Crypt_Token_Context_SetSignKeyId(GWEN_CRYPT_TOKEN_CONTEXT *st, uint32_t d) {
  assert(st);
  st->signKeyId=d;
  st->_modified=1;
}




uint32_t GWEN_Crypt_Token_Context_GetVerifyKeyId(const GWEN_CRYPT_TOKEN_CONTEXT *st) {
  assert(st);
  return st->verifyKeyId;
}


void GWEN_Crypt_Token_Context_SetVerifyKeyId(GWEN_CRYPT_TOKEN_CONTEXT *st, uint32_t d) {
  assert(st);
  st->verifyKeyId=d;
  st->_modified=1;
}




uint32_t GWEN_Crypt_Token_Context_GetEncipherKeyId(const GWEN_CRYPT_TOKEN_CONTEXT *st) {
  assert(st);
  return st->encipherKeyId;
}


void GWEN_Crypt_Token_Context_SetEncipherKeyId(GWEN_CRYPT_TOKEN_CONTEXT *st, uint32_t d) {
  assert(st);
  st->encipherKeyId=d;
  st->_modified=1;
}




uint32_t GWEN_Crypt_Token_Context_GetDecipherKeyId(const GWEN_CRYPT_TOKEN_CONTEXT *st) {
  assert(st);
  return st->decipherKeyId;
}


void GWEN_Crypt_Token_Context_SetDecipherKeyId(GWEN_CRYPT_TOKEN_CONTEXT *st, uint32_t d) {
  assert(st);
  st->decipherKeyId=d;
  st->_modified=1;
}




uint32_t GWEN_Crypt_Token_Context_GetAuthSignKeyId(const GWEN_CRYPT_TOKEN_CONTEXT *st) {
  assert(st);
  return st->authSignKeyId;
}


void GWEN_Crypt_Token_Context_SetAuthSignKeyId(GWEN_CRYPT_TOKEN_CONTEXT *st, uint32_t d) {
  assert(st);
  st->authSignKeyId=d;
  st->_modified=1;
}




uint32_t GWEN_Crypt_Token_Context_GetAuthVerifyKeyId(const GWEN_CRYPT_TOKEN_CONTEXT *st) {
  assert(st);
  return st->authVerifyKeyId;
}


void GWEN_Crypt_Token_Context_SetAuthVerifyKeyId(GWEN_CRYPT_TOKEN_CONTEXT *st, uint32_t d) {
  assert(st);
  st->authVerifyKeyId=d;
  st->_modified=1;
}




const char *GWEN_Crypt_Token_Context_GetServiceId(const GWEN_CRYPT_TOKEN_CONTEXT *st) {
  assert(st);
  return st->serviceId;
}


void GWEN_Crypt_Token_Context_SetServiceId(GWEN_CRYPT_TOKEN_CONTEXT *st, const char *d) {
  assert(st);
  if (st->serviceId)
    free(st->serviceId);
  if (d && *d)
    st->serviceId=strdup(d);
  else
    st->serviceId=0;
  st->_modified=1;
}




const char *GWEN_Crypt_Token_Context_GetUserId(const GWEN_CRYPT_TOKEN_CONTEXT *st) {
  assert(st);
  return st->userId;
}


void GWEN_Crypt_Token_Context_SetUserId(GWEN_CRYPT_TOKEN_CONTEXT *st, const char *d) {
  assert(st);
  if (st->userId)
    free(st->userId);
  if (d && *d)
    st->userId=strdup(d);
  else
    st->userId=0;
  st->_modified=1;
}




const char *GWEN_Crypt_Token_Context_GetUserName(const GWEN_CRYPT_TOKEN_CONTEXT *st) {
  assert(st);
  return st->userName;
}


void GWEN_Crypt_Token_Context_SetUserName(GWEN_CRYPT_TOKEN_CONTEXT *st, const char *d) {
  assert(st);
  if (st->userName)
    free(st->userName);
  if (d && *d)
    st->userName=strdup(d);
  else
    st->userName=0;
  st->_modified=1;
}




const char *GWEN_Crypt_Token_Context_GetPeerId(const GWEN_CRYPT_TOKEN_CONTEXT *st) {
  assert(st);
  return st->peerId;
}


void GWEN_Crypt_Token_Context_SetPeerId(GWEN_CRYPT_TOKEN_CONTEXT *st, const char *d) {
  assert(st);
  if (st->peerId)
    free(st->peerId);
  if (d && *d)
    st->peerId=strdup(d);
  else
    st->peerId=0;
  st->_modified=1;
}




const char *GWEN_Crypt_Token_Context_GetPeerName(const GWEN_CRYPT_TOKEN_CONTEXT *st) {
  assert(st);
  return st->peerName;
}


void GWEN_Crypt_Token_Context_SetPeerName(GWEN_CRYPT_TOKEN_CONTEXT *st, const char *d) {
  assert(st);
  if (st->peerName)
    free(st->peerName);
  if (d && *d)
    st->peerName=strdup(d);
  else
    st->peerName=0;
  st->_modified=1;
}




const char *GWEN_Crypt_Token_Context_GetAddress(const GWEN_CRYPT_TOKEN_CONTEXT *st) {
  assert(st);
  return st->address;
}


void GWEN_Crypt_Token_Context_SetAddress(GWEN_CRYPT_TOKEN_CONTEXT *st, const char *d) {
  assert(st);
  if (st->address)
    free(st->address);
  if (d && *d)
    st->address=strdup(d);
  else
    st->address=0;
  st->_modified=1;
}




int GWEN_Crypt_Token_Context_GetPort(const GWEN_CRYPT_TOKEN_CONTEXT *st) {
  assert(st);
  return st->port;
}


void GWEN_Crypt_Token_Context_SetPort(GWEN_CRYPT_TOKEN_CONTEXT *st, int d) {
  assert(st);
  st->port=d;
  st->_modified=1;
}




const char *GWEN_Crypt_Token_Context_GetSystemId(const GWEN_CRYPT_TOKEN_CONTEXT *st) {
  assert(st);
  return st->systemId;
}


void GWEN_Crypt_Token_Context_SetSystemId(GWEN_CRYPT_TOKEN_CONTEXT *st, const char *d) {
  assert(st);
  if (st->systemId)
    free(st->systemId);
  if (d && *d)
    st->systemId=strdup(d);
  else
    st->systemId=0;
  st->_modified=1;
}




int GWEN_Crypt_Token_Context_IsModified(const GWEN_CRYPT_TOKEN_CONTEXT *st) {
  assert(st);
  return st->_modified;
}


void GWEN_Crypt_Token_Context_SetModified(GWEN_CRYPT_TOKEN_CONTEXT *st, int i) {
  assert(st);
  st->_modified=i;
}


void GWEN_Crypt_Token_Context_Attach(GWEN_CRYPT_TOKEN_CONTEXT *st) {
  assert(st);
  st->_usage++;
}
GWEN_CRYPT_TOKEN_CONTEXT *GWEN_Crypt_Token_Context_List2__freeAll_cb(GWEN_CRYPT_TOKEN_CONTEXT *st, void *user_data) {
  GWEN_Crypt_Token_Context_free(st);
return 0;
}


void GWEN_Crypt_Token_Context_List2_freeAll(GWEN_CRYPT_TOKEN_CONTEXT_LIST2 *stl) {
  if (stl) {
    GWEN_Crypt_Token_Context_List2_ForEach(stl, GWEN_Crypt_Token_Context_List2__freeAll_cb, 0);
    GWEN_Crypt_Token_Context_List2_free(stl); 
  }
}


GWEN_CRYPT_TOKEN_CONTEXT_LIST *GWEN_Crypt_Token_Context_List_dup(const GWEN_CRYPT_TOKEN_CONTEXT_LIST *stl) {
  if (stl) {
    GWEN_CRYPT_TOKEN_CONTEXT_LIST *nl;
    GWEN_CRYPT_TOKEN_CONTEXT *e;

    nl=GWEN_Crypt_Token_Context_List_new();
    e=GWEN_Crypt_Token_Context_List_First(stl);
    while(e) {
      GWEN_CRYPT_TOKEN_CONTEXT *ne;

      ne=GWEN_Crypt_Token_Context_dup(e);
      assert(ne);
      GWEN_Crypt_Token_Context_List_Add(ne, nl);
      e=GWEN_Crypt_Token_Context_List_Next(e);
    } /* while (e) */
    return nl;
  }
  else
    return 0;
}




