/* This file is auto-generated from "ct_context.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef CT_CONTEXT_P_H
#define CT_CONTEXT_P_H

#include "ct_context_l.h"


struct GWEN_CRYPT_TOKEN_CONTEXT {
  GWEN_INHERIT_ELEMENT(GWEN_CRYPT_TOKEN_CONTEXT)
  GWEN_LIST_ELEMENT(GWEN_CRYPT_TOKEN_CONTEXT)
  int _usage;
  int _modified;

  uint32_t id;
  uint32_t signKeyId;
  uint32_t verifyKeyId;
  uint32_t encipherKeyId;
  uint32_t decipherKeyId;
  uint32_t authSignKeyId;
  uint32_t authVerifyKeyId;
  char *serviceId;
  char *userId;
  char *userName;
  char *peerId;
  char *peerName;
  char *address;
  int port;
  char *systemId;
};



/** @name Key Ids
 *
This group contains the ids of the keys for multiple given purposes which are to be used in this context.*/
/*@{*/







/*@}*/

/** @name User Information
 *
This group contains some information about this context. With some crypt token user information might be available with a context.*/
/*@{*/









/*@}*/


#endif /* CT_CONTEXT_P_H */
