/* This file is auto-generated from "ct_context.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef CT_CONTEXT_L_H
#define CT_CONTEXT_L_H

/** @page P_GWEN_CRYPT_TOKEN_CONTEXT_LIB GWEN_Crypt_Token_Context (lib)
This page describes the properties of GWEN_CRYPT_TOKEN_CONTEXT
<h3>Key Ids</h3>
<p>
This group contains the ids of the keys for multiple given purposes which are to be used in this context.</p>
<h3>User Information</h3>
<p>
This group contains some information about this context. With some crypt token user information might be available with a context.</p>
*/
#include "ct_context.h"

#ifdef __cplusplus
extern "C" {
#endif




/** @name Key Ids
 *
This group contains the ids of the keys for multiple given purposes which are to be used in this context.*/
/*@{*/







/*@}*/

/** @name User Information
 *
This group contains some information about this context. With some crypt token user information might be available with a context.*/
/*@{*/









/*@}*/


#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* CT_CONTEXT_L_H */
