/**********************************************************
 * This file has been automatically created by "typemaker2"
 * from the file "ct_context.xml".
 * Please do not edit this file, all changes will be lost.
 * Better edit the mentioned source file instead.
 **********************************************************/

#ifndef CT_CONTEXT_P_H
#define CT_CONTEXT_P_H

#include "ct_context.h"


#ifdef __cplusplus
extern "C" {
#endif

struct GWEN_CRYPT_TOKEN_CONTEXT {
  GWEN_INHERIT_ELEMENT(GWEN_CRYPT_TOKEN_CONTEXT)
  GWEN_LIST_ELEMENT(GWEN_CRYPT_TOKEN_CONTEXT)
  int _refCount;
  uint32_t id;
  uint32_t signKeyId;
  uint32_t verifyKeyId;
  uint32_t encipherKeyId;
  uint32_t decipherKeyId;
  uint32_t authSignKeyId;
  uint32_t authVerifyKeyId;
  uint32_t tempSignKeyId;
  char *serviceId;
  char *userId;
  char *customerId;
  char *userName;
  char *peerId;
  char *peerName;
  char *address;
  int port;
  char *systemId;
  /**** RDH7 Block Start******/
  uint32_t keyHashNum;
  uint32_t keyHashVer;
  uint32_t keyHashAlgo;
  uint32_t keyHashLen;
  int      keyStatus;
  char*    keyHash;
  uint32_t rdhVersion;
  char*    cid;
  /**** RDH7 Block End******/
};

#ifdef __cplusplus
}
#endif

#endif

