/**********************************************************
 * This file has been automatically created by "typemaker2"
 * from the file "ct_keyinfo.xml".
 * Please do not edit this file, all changes will be lost.
 * Better edit the mentioned source file instead.
 **********************************************************/

#ifndef GWEN_CRYPT_TOKEN_KEYINFO_CT_KEYINFO_P_H
#define GWEN_CRYPT_TOKEN_KEYINFO_CT_KEYINFO_P_H

#include "ct_keyinfo.h"


#ifdef __cplusplus
extern "C" {
#endif

struct GWEN_CRYPT_TOKEN_KEYINFO {
  GWEN_INHERIT_ELEMENT(GWEN_CRYPT_TOKEN_KEYINFO)
  GWEN_LIST_ELEMENT(GWEN_CRYPT_TOKEN_KEYINFO)
  int _refCount;
  uint32_t id;
  char *keyDescr;
  uint32_t flags;
  int keySize;
  int cryptAlgoId;
  GWEN_BUFFER *modulus;
  GWEN_BUFFER *exponent;
  uint32_t keyNumber;
  uint32_t keyVersion;
  uint32_t signCounter;
  GWEN_BUFFER *certificate;
  uint8_t certType;
};

/** Private constructor. */
GWEN_CRYPT_TOKEN_KEYINFO *GWEN_Crypt_Token_KeyInfo__new(void);

#ifdef __cplusplus
}
#endif

#endif

