/* This file is auto-generated from "st_log.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef ST_LOG_P_H
#define ST_LOG_P_H

#include "st_log_l.h"


struct GWEN_STO_LOG {
  GWEN_LIST_ELEMENT(GWEN_STO_LOG)
  int _usage;
  int _modified;

  char *userName;
  GWEN_STO_LOG_ACTION logAction;
  char *typeBaseName;
  char *typeName;
  GWEN_TYPE_UINT32 objectId;
  char *param1;
  char *param2;
  char *param3;
};












#endif /* ST_LOG_P_H */
