/* This file is auto-generated from "st_vardef.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef ST_VARDEF_L_H
#define ST_VARDEF_L_H

/** @page P_GWEN_STO_VARDEF_LIB GWEN_StoVarDef (lib)
This page describes the properties of GWEN_STO_VARDEF
*/
#include "st_vardef.h"

#ifdef __cplusplus
extern "C" {
#endif







#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* ST_VARDEF_L_H */
