/* This file is auto-generated from "st_vardef.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef ST_VARDEF_P_H
#define ST_VARDEF_P_H

#include "st_vardef_l.h"


struct GWEN_STO_VARDEF {
  GWEN_LIST_ELEMENT(GWEN_STO_VARDEF)
  int _usage;
  int _modified;

  char *name;
  int minNum;
  int maxNum;
};






#endif /* ST_VARDEF_P_H */
