/**********************************************************
 * This file has been automatically created by "typemaker2"
 * from the file "test.xml".
 * Please do not edit this file, all changes will be lost.
 * Better edit the mentioned source file instead.
 **********************************************************/

#ifndef TEST_H
#define TEST_H


#ifdef __cplusplus
extern "C" {
#endif

/* define TEST_DEF */
#define TEST_DEFINE_VALUE1 1
#define TEST_DEFINE_VALUE2 2
#define TEST_DEFINE_VALUE3 4
#define TEST_DEFINE_VALUE4 8
#define TEST_DEFINE_VALUEx 255


/* needed system headers */
#include <gwenhywfar/types.h>
#include <gwenhywfar/list1.h>
#include <gwenhywfar/xml.h>

/* pre-headers */
#include "tm_item.h"

typedef struct TEST TEST;
GWEN_LIST_FUNCTION_LIB_DEFS(TEST, Test, GWENHYWFAR_API)

/* post-headers */


enum {
  Test_Mode_Unknown = 0,
  Test_Mode_Sequence = 1,
  Test_Mode_BitField
};


GWENHYWFAR_API int Test_Mode_fromString(const char *p_s);

GWENHYWFAR_API const char *Test_Mode_toString(int p_i);

/** Constructor. */
GWENHYWFAR_API TEST *Test_new();

/** Destructor. */
GWENHYWFAR_API void Test_free(TEST *p_struct);

GWENHYWFAR_API TEST *Test_dup(const TEST *p_struct);

/** Getter.
 * Use this function to get the member "id"
*/
GWENHYWFAR_API const char *Test_GetId(const TEST *p_struct);

/** Getter.
 * Use this function to get the member "prefix"
*/
GWENHYWFAR_API const char *Test_GetPrefix(const TEST *p_struct);

/** Getter.
 * Use this function to get the member "type"
*/
GWENHYWFAR_API const char *Test_GetType(const TEST *p_struct);

/** Getter.
 * Use this function to get the member "items"
*/
GWENHYWFAR_API TYPEMAKER2_ITEM_LIST *Test_GetItems(const TEST *p_struct);

/** Getter.
 * Use this function to get the member "mode"
*/
GWENHYWFAR_API int Test_GetMode(const TEST *p_struct);

/** Setter.
 * Use this function to set the member "id"
*/
GWENHYWFAR_API void Test_SetId(TEST *p_struct, const char *p_src);

/** Setter.
 * Use this function to set the member "prefix"
*/
GWENHYWFAR_API void Test_SetPrefix(TEST *p_struct, const char *p_src);

/** Setter.
 * Use this function to set the member "type"
*/
GWENHYWFAR_API void Test_SetType(TEST *p_struct, const char *p_src);

/** Setter.
 * Use this function to set the member "items"
*/
GWENHYWFAR_API void Test_SetItems(TEST *p_struct, const TYPEMAKER2_ITEM_LIST *p_src);

/** Setter.
 * Use this function to set the member "mode"
*/
GWENHYWFAR_API void Test_SetMode(TEST *p_struct, int p_src);

GWENHYWFAR_API void Test_ReadXml(TEST *p_struct, GWEN_XMLNODE *p_db);

GWENHYWFAR_API void Test_WriteXml(const TEST *p_struct, GWEN_XMLNODE *p_db);

GWENHYWFAR_API void Test_toXml(const TEST *p_struct, GWEN_XMLNODE *p_db);

GWENHYWFAR_API TEST *Test_fromXml(GWEN_XMLNODE *p_db);

#ifdef __cplusplus
}
#endif

#endif

