/**********************************************************
 * This file has been automatically created by "typemaker2"
 * from the file "test.tm2".
 * Please do not edit this file, all changes will be lost.
 * Better edit the mentioned source file instead.
 **********************************************************/

#ifndef TEST_L_H
#define TEST_L_H

#include "test_be.h"


#ifdef __cplusplus
extern "C" {
#endif

/** Getter.
 * Use this function to get the member "id"
*/
uint32_t Test_GetId(const TEST *p_struct);

/** Setter.
 * Use this function to set the member "id"
*/
void Test_SetId(TEST *p_struct, uint32_t p_src);

#ifdef __cplusplus
}
#endif

#endif

