/**********************************************************
 * This file has been automatically created by "typemaker2"
 * from the file "test.xml".
 * Please do not edit this file, all changes will be lost.
 * Better edit the mentioned source file instead.
 **********************************************************/

#ifdef HAVE_CONFIG_H
# include <config.h>
#endif

#include "test_p.h"

#include <gwenhywfar/misc.h>
#include <gwenhywfar/debug.h>

/* code headers */

/* macro functions */
GWEN_LIST_FUNCTIONS(TEST, Test)


int Test_Mode_fromString(const char *p_s) {
  if (p_s && *p_s) {
    if (strcasecmp(p_s, "sequence")==0)
      return Test_Mode_Sequence;
    else if (strcasecmp(p_s, "bitField")==0)
      return Test_Mode_BitField;
  }
  return Test_Mode_Unknown;
}

const char *Test_Mode_toString(int p_i) {
  switch(p_i) {
    case Test_Mode_Sequence: return "sequence";
    case Test_Mode_BitField: return "bitField";
    default: return "unknown";
  }
}

TEST *Test_new() {
  TEST *p_struct;

  GWEN_NEW_OBJECT(TEST, p_struct)
  GWEN_LIST_INIT(TEST, p_struct)
  /* members */
  p_struct->id=NULL;
  p_struct->prefix=NULL;
  p_struct->type=NULL;
  
  

  return p_struct;
}

void Test_free(TEST *p_struct) {
  if (p_struct) {
    GWEN_LIST_FINI(TEST, p_struct)
  /* members */
    free(p_struct->id);
    free(p_struct->prefix);
    free(p_struct->type);
    
    
    GWEN_FREE_OBJECT(p_struct);
  }
}

TEST *Test_dup(const TEST *p_src) {
  TEST *p_struct;

  assert(p_src);
  p_struct=Test_new();
  /* member "id" */
  if (p_struct->id) {
    free(p_struct->id);
    p_struct->id=NULL;
  }
  if (p_src->id) {
    p_struct->id=strdup(p_src->id);
  }

  /* member "prefix" */
  if (p_struct->prefix) {
    free(p_struct->prefix);
    p_struct->prefix=NULL;
  }
  if (p_src->prefix) {
    p_struct->prefix=strdup(p_src->prefix);
  }

  /* member "type" */
  if (p_struct->type) {
    free(p_struct->type);
    p_struct->type=NULL;
  }
  if (p_src->type) {
    p_struct->type=strdup(p_src->type);
  }

  /* member "items" */
  if (p_struct->items) {
    
    p_struct->items=NULL;
  }
  if (p_src->items) {
    
  }

  /* member "mode" */
  

  return p_struct;
}

const char *Test_GetId(const TEST *p_struct) {
  assert(p_struct);
  return p_struct->id;
}

const char *Test_GetPrefix(const TEST *p_struct) {
  assert(p_struct);
  return p_struct->prefix;
}

const char *Test_GetType(const TEST *p_struct) {
  assert(p_struct);
  return p_struct->type;
}

TYPEMAKER2_ITEM_LIST *Test_GetItems(const TEST *p_struct) {
  assert(p_struct);
  return p_struct->items;
}

int Test_GetMode(const TEST *p_struct) {
  assert(p_struct);
  return p_struct->mode;
}

void Test_SetId(TEST *p_struct, const char *p_src) {
  assert(p_struct);
  if (p_struct->id) {
    free(p_struct->id);
  }
  if (p_src) {
    p_struct->id=strdup(p_src);
  }
  else {
    p_struct->id=NULL;
  }
}

void Test_SetPrefix(TEST *p_struct, const char *p_src) {
  assert(p_struct);
  if (p_struct->prefix) {
    free(p_struct->prefix);
  }
  if (p_src) {
    p_struct->prefix=strdup(p_src);
  }
  else {
    p_struct->prefix=NULL;
  }
}

void Test_SetType(TEST *p_struct, const char *p_src) {
  assert(p_struct);
  if (p_struct->type) {
    free(p_struct->type);
  }
  if (p_src) {
    p_struct->type=strdup(p_src);
  }
  else {
    p_struct->type=NULL;
  }
}

void Test_SetItems(TEST *p_struct, const TYPEMAKER2_ITEM_LIST *p_src) {
  assert(p_struct);
  if (p_struct->items) {
    
  }
  if (p_src) {
    
  }
  else {
    
  }
}

void Test_SetMode(TEST *p_struct, int p_src) {
  assert(p_struct);
  
}

void Test_ReadXml(TEST *p_struct, GWEN_XMLNODE *p_db) {
  assert(p_struct);
  /* member "id" */
  if (p_struct->id) {
    free(p_struct->id);
  }
  p_struct->id=NULL;
  { const char *s; s=GWEN_XMLNode_GetProperty(p_db, "id", NULL); if (s) p_struct->id=strdup(s); }

  /* member "prefix" */
  if (p_struct->prefix) {
    free(p_struct->prefix);
  }
  p_struct->prefix=NULL;
  { const char *s; s=GWEN_XMLNode_GetProperty(p_db, "prefix", NULL); if (s) p_struct->prefix=strdup(s); }

  /* member "type" */
  if (p_struct->type) {
    free(p_struct->type);
  }
  p_struct->type=NULL;
  { const char *s; s=GWEN_XMLNode_GetProperty(p_db, "type", NULL); if (s) p_struct->type=strdup(s); }

  /* member "items" */
  if (p_struct->items) {
    
  }
  
  /* member "items" is volatile, not reading from xml */

  /* member "mode" */
  
  

}

void Test_WriteXml(const TEST *p_struct, GWEN_XMLNODE *p_db) {
  assert(p_struct);
  /* member "id" */
  GWEN_XMLNode_SetProperty(p_db, "id", p_struct->id);

  /* member "prefix" */
  GWEN_XMLNode_SetProperty(p_db, "prefix", p_struct->prefix);

  /* member "type" */
  GWEN_XMLNode_SetProperty(p_db, "type", p_struct->type);

  /* member "items" is volatile, not writing to xml */

  /* member "mode" */
  

}

void Test_toXml(const TEST *p_struct, GWEN_XMLNODE *p_db) {
  Test_WriteXml(p_struct, p_db);
}

TEST *Test_fromXml(GWEN_XMLNODE *p_db) {
  TEST *p_struct;
  p_struct=Test_new();
  Test_ReadXml(p_struct, p_db);
  return p_struct;
}

