/**********************************************************
 * This file has been automatically created by "typemaker2"
 * from the file "test.xml".
 * Please do not edit this file, all changes will be lost.
 * Better edit the mentioned source file instead.
 **********************************************************/

#ifndef TEST_P_H
#define TEST_P_H

#include "test.h"


#ifdef __cplusplus
extern "C" {
#endif

struct TEST {
  GWEN_LIST_ELEMENT(TEST)
  char *id;
  char *prefix;
  char *type;
  TYPEMAKER2_ITEM_LIST *items; /* volatile */
  int mode;
};

#ifdef __cplusplus
}
#endif

#endif

