/**********************************************************
 * This file has been automatically created by "typemaker2"
 * from the file "test.tm2".
 * Please do not edit this file, all changes will be lost.
 * Better edit the mentioned source file instead.
 **********************************************************/

#ifndef TEST_P_H
#define TEST_P_H

#include "test_l.h"


#ifdef __cplusplus
extern "C" {
#endif

#define TEST_FIELD_CHARPOINTER 0
#define TEST_FIELD_CHARARRAY 1
#define TEST_FIELD_CHARPOINTERNODUP 2
#define TEST_FIELD_CHARPOINTERPRIVATE 3
#define TEST_FIELD_COUNT 4

struct TEST {
  GWEN_INHERIT_ELEMENT(TEST)
  GWEN_LIST_ELEMENT(TEST)
  uint32_t id; /* volatile */
  char *charPointer;
  char charArray[32];
  char *charPointerNoDup;
  char *charPointerPrivate;
};

/** Getter.
 * Use this function to get the member "charPointerPrivate"
*/
const char *Test_GetCharPointerPrivate(const TEST *p_struct);

/** Setter.
 * Use this function to set the member "charPointerPrivate"
*/
void Test_SetCharPointerPrivate(TEST *p_struct, const char *p_src);

#ifdef __cplusplus
}
#endif

#endif

