/**********************************************************
 * This file has been automatically created by "typemaker2"
 * from the file "test.xml".
 * Please do not edit this file, all changes will be lost.
 * Better edit the mentioned source file instead.
 **********************************************************/

#ifndef TEST_BE_H
#define TEST_BE_H

#include "test.h"


#ifdef __cplusplus
extern "C" {
#endif

/** Getter.
 * Use this function to get the member "charPointerNoDup"
*/
GWENHYWFAR_API const char *Test_GetCharPointerNoDup(const TEST *p_struct);

/** Setter.
 * Use this function to set the member "charPointerNoDup"
*/
GWENHYWFAR_API void Test_SetCharPointerNoDup(TEST *p_struct, const char *p_src);

#ifdef __cplusplus
}
#endif

#endif

