/**********************************************************
 * This file has been automatically created by "typemaker2"
 * from the file "tm_code.xml".
 * Please do not edit this file, all changes will be lost.
 * Better edit the mentioned source file instead.
 **********************************************************/

#ifndef TM_CODE_P_H
#define TM_CODE_P_H

#include "tm_code.h"


#ifdef __cplusplus
extern "C" {
#endif

struct TYPEMAKER2_CODE {
  GWEN_LIST_ELEMENT(TYPEMAKER2_CODE)
  char *id;
  char *memberFlagsMask;
  char *memberFlagsValue;
  char *code;
  uint32_t memberFlagsMaskInt; /* volatile */
  uint32_t memberFlagsValueInt; /* volatile */
};

#ifdef __cplusplus
}
#endif

#endif

