/**********************************************************
 * This file has been automatically created by "typemaker2"
 * from the file "tm_enum.xml".
 * Please do not edit this file, all changes will be lost.
 * Better edit the mentioned source file instead.
 **********************************************************/

#ifndef TM_ENUM_P_H
#define TM_ENUM_P_H

#include "tm_enum.h"


#ifdef __cplusplus
extern "C" {
#endif

struct TYPEMAKER2_ENUM {
  GWEN_LIST_ELEMENT(TYPEMAKER2_ENUM)
  char *id;
  char *prefix;
  char *type;
  TYPEMAKER2_ITEM_LIST *items; /* volatile */
  char *toStringFn; /* volatile */
  char *fromStringFn; /* volatile */
};

#ifdef __cplusplus
}
#endif

#endif

