/* This file is auto-generated from "ssl_cipher.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef SSL_CIPHER_L_H
#define SSL_CIPHER_L_H

/** @page P_GWEN_SSLCIPHER_LIB GWEN_SslCipher (lib)
This page describes the properties of GWEN_SSLCIPHER
*/
#include "ssl_cipher.h"

#ifdef __cplusplus
extern "C" {
#endif








#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* SSL_CIPHER_L_H */
