/* This file is auto-generated from "ssl_cert_descr.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef SSL_CERT_DESCR_L_H
#define SSL_CERT_DESCR_L_H

/** @page P_GWEN_SSLCERTDESCR_LIB GWEN_SslCertDescr (lib)
This page describes the properties of GWEN_SSLCERTDESCR
*/
#include "ssl_cert_descr.h"

#ifdef __cplusplus
extern "C" {
#endif



















#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* SSL_CERT_DESCR_L_H */
