/* This file is auto-generated from "ssl_cipher.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef SSL_CIPHER_P_H
#define SSL_CIPHER_P_H

#include "ssl_cipher_l.h"


struct GWEN_SSLCIPHER {
  GWEN_LIST_ELEMENT(GWEN_SSLCIPHER)
  int _usage;
  int _modified;

  char *name;
  char *version;
  char *description;
  int bits;
};







#endif /* SSL_CIPHER_P_H */
